techexpert37b/freemarket_sample_37b

app/controllers/application_controller.rb
create basic confirm
to lock web site
=> Add-basic_confirm

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_sell-btn.scss, app/views/layouts/application.html.haml, app/views/shared/_sell-btn.html.haml
=> Create sell btn

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/models/user.rb, app/views/devise/confirmations/new.html.haml, app/views/devise/mailer/confirmation_instructions.html.haml, app/views/devise/mailer/email_changed.html.haml, app/views/devise/mailer/password_change.html.haml, app/views/devise/mailer/reset_password_instructions.html.haml, app/views/devise/mailer/unlock_instructions.html.haml, app/views/devise/passwords/edit.html.haml, app/views/devise/passwords/new.html.haml, app/views/devise/registrations/edit.html.haml, app/views/devise/registrations/new.html.haml, app/views/devise/sessions/new.html.haml, app/views/devise/shared/_links.html.haml, app/views/devise/unlocks/new.html.haml, app/views/items/index.html.haml, app/views/layouts/application.html.haml, app/views/shared/_header.html.haml, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20181027061513_devise_create_users.rb, db/schema.rb
install device
to add user registration fubction
=> Make basic_device

README.md
データベース設計の変更
メルカリの仕様上nickname,email,passwordがあればアカウント登録ができる為
=> edit_databese_design

app/views/layouts/application.html.haml, app/views/layouts/mailer.html.haml, app/views/mypages/_sidebar.html.haml, app/views/mypages/logout.html.haml, app/views/shared/_app-banner.html.haml, app/views/shared/_footer.html.haml, app/views/shared/_header.html.haml, app/views/shared/_mypage.html.haml, app/views/shared/_sell-btn.html.haml, app/views/shared/_top-main-visual.html.haml
=> Modify-view_code

app/controllers/users_controller.rb, config/routes.rb
コントローラー、ルーティングの作成
ユーザーまわりの実装のため
=> create user controller and routes

app/models/address.rb, app/models/user.rb, db/migrate/20181031081305_create_addresses.rb, db/schema.rb
＃ what
install an address model
to use an address model
=> Install-address_model

README.md
db設計の変更
メルカリのユーザー登録の仕様は新規登録（nickname, emaill, password）→電話番号登録→アカウント登録完了→住所登録(firstname, familyname, familyname_kana,first_name_kana postal_code, prefecture, city, street_number)
であり、住所登録のビュ一１画面で登録したuser情報のアップデートをし住所情報を新規登録するフォームを作ることは１アクションで複数モデルのアップデートとクリエイトを同時に行うことになり構造上おそらく無理であるため。また現時点でも７つのアクション以外のアクションを複数生成しており、ネストやパスも複雑になっているため非常に可読性が落ちているため
コネクトに相談してもファミリーネーム等は住所と同じテーブルにあるのが妥当と判断しており、これ以上の複雑な設計は無駄であるため
=> Change-db_design

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_header.scss, app/assets/stylesheets/users/_login.scss, app/assets/stylesheets/users/_mypage.footer.scss, app/assets/stylesheets/users/_mypage.header.scss, app/assets/stylesheets/users/registraions.index.scss, app/views/devise/registrations/index.html.haml, app/views/devise/sessions/new.html.haml, app/views/mypages/_mypage.footer.html.haml, app/views/mypages/_mypage.header.html.haml, app/views/shared/_header.html.haml
Modify sentences
Improve readability
=> Edit mypage files

app/assets/stylesheets/application.scss, app/assets/stylesheets/items/_index.scss, app/assets/stylesheets/items/_show.scss, app/assets/stylesheets/modules/_header.scss, app/assets/stylesheets/modules/_items-box.scss, app/controllers/items_controller.rb, app/views/items/show.html.haml, db/migrate/20181027061513_init_schema.rb
商品詳細ページの実装
必須の為
※ 画像表示/いいね/SNSアイコン/コメント機能は後日追加
[![Screenshot from Gyazo](https://gyazo.com/675f4f0f5422f96eba971cfff9128ac4/raw)](https://gyazo.com/675f4f0f5422f96eba971cfff9128ac4)
=> Create items show page

app/assets/stylesheets/modules/_header.scss, app/assets/stylesheets/modules/_logout.scss, app/views/users/logout.html.haml
ヘッダーのボタン２つの位置を修正しました。
ログアウトボタンを修正しました。
ログアウトページにヘッダーとフッダーを追加しました
=> トップページヘッダーとログアウトのボタン修正

app/controllers/users_controller.rb, config/routes.rb
=> プロフィール画面の作成

app/assets/stylesheets/application.scss, app/assets/stylesheets/users/_new.scss, app/views/devise/registrations/new.html.haml
=> create signup view

.gitignore, Gemfile, Gemfile.lock, app/controllers/addresses_controller.rb, app/controllers/payments_controller.rb, app/models/payment.rb, app/models/user.rb, app/views/payments/new.html.haml, config/routes.rb, db/migrate/20181103080417_create_payments.rb, db/schema.rb
make credit card registration function
for user to use credit card payment
=> Make credit registration function

app/views/devise/registrations/new.html.haml
modify registration view
to use registration function
=> Modify-registration_view

app/assets/stylesheets/application.scss, app/assets/stylesheets/items/_index.scss, app/assets/stylesheets/modules/_logout.scss, app/assets/stylesheets/payments/_edit.scss, app/controllers/payments_controller.rb, app/views/layouts/application.html.haml, app/views/layouts/mypages.html.haml, app/views/mypages/_sidebar.html.haml, app/views/payments/edit.html.haml, app/views/shared/_mypage.html.haml, app/views/users/logout.html.haml, config/routes.rb
ユーザークレジットカード登録ページの実装
必須の為
[![Screenshot from Gyazo](https://gyazo.com/a6b4eb419a7b2168b93d77a83f20a895/raw)](https://gyazo.com/a6b4eb419a7b2168b93d77a83f20a895)
=> Create payment edit

app/models/address.rb, app/models/payment.rb, app/models/user.rb
change validation
to forbid dual email address and so on
=> Modify-user_validation

.gitignore
make .env.production file 
to use envioment number in production
=> Make-env_file_for_production

.gitignore
change env
to use enviroment number in production
=> Fix_env_file

config/application.rb
add japanese style
to show form
=> Add-japanese

app/models/item.rb, db/migrate/20181108034937_create_items.rb, db/schema.rb
=> Install-item_model

app/controllers/items_controller.rb, app/models/delivery.rb, app/models/item.rb, app/models/user.rb, app/views/items/new.html.haml, app/views/shared/_sell-btn.html.haml, config/routes.rb, db/migrate/20181108083151_change_data_type_of_items.rb, db/migrate/20181108083723_create_deliveries.rb, db/schema.rb
make item supply function
for user to sell items
=> Make item sell function

README.md
データベース設計のphotosテーブルカラムの変更
photoを保存しやすくするため
=> change-photos_db_design

app/assets/javascripts/price.js, app/models/item.rb, app/views/items/new.html.haml
＃ what
make price calculation function
to get fee
=> Make-price_function

app/controllers/items_controller.rb, app/views/items/index.html.haml, app/views/items/new.html.haml, app/views/mypages/_mypage.header.html.haml, app/views/shared/_items-box.html.haml, app/views/shared/_sell-btn.html.haml, config/routes.rb
make item list function
for user to see new item
=> Make item index function

app/controllers/items_controller.rb, app/models/item.rb, app/views/items/show.html.haml
edit item index and show
to improve item function
=> Edit-item_details

app/assets/stylesheets/modules/_payments.new.scss, app/views/payments/new.html.haml, app/views/shared/_sell-btn.html.haml
edit payjp button css
for user to click easy
=> Edit-payment_registration_button

app/assets/stylesheets/config/_common.scss, app/assets/stylesheets/modules/_logout.scss, app/assets/stylesheets/modules/_mypage.scss, app/controllers/addresses_controller.rb, app/controllers/payments_controller.rb, app/controllers/users_controller.rb, app/views/devise/sessions/new.html.haml, app/views/mypages/_sidebar.html.haml, app/views/payments/edit.html.haml, app/views/users/logout.html.haml
=> #2 refactoring
